version: "3"

services:
  db2:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: link_db_2
      POSTGRES_USER: link_db_2
      POSTGRES_PASSWORD: link_db_2
      POSTGRES_HOST: db2
      POSTGRES_PORT: 5432
    volumes:
      - data2:/var/lib/postgresql/data
  app2:
    build: ./
    restart: always
    ports:
      - "81:8000"  # Изменим порт, чтобы избежать конфликта
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db2
volumes:
  data2:

