version: '3.1'

services:
  app:
    build: .
    env_file:
      - .env
    command: bash -c "python manage.py migrate  && python manage.py runserver 0.0.0.0:8800"
    volumes:
      - .:/app
    ports:
      - 8800:8800
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgresDb:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgresDb:
