# Generated by Django 4.1.2 on 2022-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='country_name'),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=255, verbose_name='link_name'),
        ),
    ]
