# Generated by Django 4.1.9 on 2023-09-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_link',
            name='country_name',
            field=models.ManyToManyField(related_name='country_link', to='main.country'),
        ),
        migrations.AlterField(
            model_name='country_link',
            name='link_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_link', to='main.url', verbose_name='url_id'),
        ),
    ]
