# Generated by Django 4.1.9 on 2023-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_country_link_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_link',
            name='new_url',
            field=models.CharField(max_length=255, unique=True, verbose_name='new_link'),
        ),
    ]
