# Generated by Django 4.1.2 on 2023-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_url_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
