# Generated by Django 4.1.2 on 2023-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_url_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_link',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
